import os

DOXYFILE = 'Doxyfile-mcss'

STYLESHEETS = [
    'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,600i%7CSource+Code+Pro:400,400i,600',
    'third_party/m.css/css/m-dark+documentation.compiled.css'
]

THEME_COLOR = '#22272e'
FAVICON = 'third_party/m.css/documentation/favicon-dark.png'

LINKS_NAVBAR1 = [
    ("Namespaces", 'namespaces', []),
    ("Classes", 'annotated', []),
]
LINKS_NAVBAR2 = [
    ("Files", 'files', []),
]

FINE_PRINT = "Game Engine. Generated by {doxygen_version} and m.css."
